### ISSUE TITLE
Server side rendering issues

### ISSUE THREAD

**Issue by adomrockie** [buildo/react-cookie-banner#41]
Hi guys, can we merge the waiting pull request to use react-cookies with SSR?

Currently having invalid checksum issues with server side rendering.

**Comment by FrancescoCioria** [comment]
Hi @adomrockie , unfortunately that PR is no longer mergeable.
we can work on a new solution

**Comment by adomrockie** [comment]
Thanks, that will be great. Is this something you looking to do soon? or should we do it ourselves.

**Comment by FrancescoCioria** [comment]
I already started looking into it and was planning to open a PR within the following week, but of course PRs are welcome if you need it sooner :)

**Comment by FrancescoCioria** [comment]
nevermind, I already opened the PR 😬 
you can check the code in #42 , what do you think? 
(I'm new to SSR so I might have done some stupid mistakes)
