### ISSUE TITLE
Documentation of link prop is obsolete

### ISSUE THREAD

**Issue by CorwinCZ** [buildo/react-cookie-banner#56]
Current documentation of `link` prop found [here](https://github.com/buildo/react-cookie-banner/blob/master/src/README.md) is out-dated. Current implementation required JSX element instead of object - as found [here](https://github.com/buildo/react-cookie-banner/blob/master/src/BannerContent.tsx)

Documentation can be updated this way (line 11):

```
| **link** | ```<a href="http://demo.url" target="_blank">Link text</a>``` |  | *optional*. JSX element to link to your cookie-policy page |
```
Originaly I wanted to create PR for this issue, but it is not possible to push new branch to repository.

**Comment by gabro** [comment]
@CorwinCZ thanks for reporting the issue :) 

You can't publish a branch to this repository, but you can fork it, push the fix on your fork and submit a PR from there, as explained in https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks!
